import type { GameSummaryDTO } from "@sportlink/types";

const host = (id: string, name: string): GameSummaryDTO["host"] => ({
  id,
  name,
  verificationStatus: "fully_verified",
});

export const MOCK_GAMES: GameSummaryDTO[] = [
  {
    id: "mock-soccer-1",
    title: "Sunday morning kickabout",
    sport: "soccer",
    skillLevel: "intermediate",
    gender: "open",
    dateTime: "2026-05-17T09:00:00+10:00",
    location: {
      lat: -33.8742,
      lng: 151.2391,
      address: "Rushcutters Bay Park, New South Head Rd, Rushcutters Bay NSW",
      suburb: "Rushcutters Bay Park",
    },
    distanceKm: 3.2,
    minPlayers: 10,
    maxPlayers: 18,
    currentPlayers: 7,
    costPerPlayer: 0,
    status: "open",
    host: host("host-1", "Mia Carter"),
  },
  {
    id: "mock-soccer-2",
    title: "5-a-side Tuesday evening",
    sport: "soccer",
    skillLevel: "competitive",
    gender: "men",
    dateTime: "2026-05-19T18:30:00+10:00",
    location: {
      lat: -33.8931,
      lng: 151.2016,
      address: "Sydney Park Rd, Alexandria NSW",
      suburb: "Sydney Park",
    },
    distanceKm: 6.8,
    minPlayers: 8,
    maxPlayers: 10,
    currentPlayers: 9,
    costPerPlayer: 500,
    status: "open",
    host: host("host-2", "Theo Nguyen"),
  },
  {
    id: "mock-basketball-1",
    title: "Casual 3v3 pickup",
    sport: "basketball",
    skillLevel: "beginner",
    gender: "open",
    dateTime: "2026-05-16T10:00:00+10:00",
    location: {
      lat: -33.8917,
      lng: 151.224,
      address: "Cnr Anzac Pde and Lang Rd, Moore Park NSW",
      suburb: "Moore Park Courts",
    },
    distanceKm: 11.4,
    minPlayers: 4,
    maxPlayers: 6,
    currentPlayers: 2,
    costPerPlayer: 0,
    status: "open",
    host: host("host-3", "Ava Singh"),
  },
  {
    id: "mock-volleyball-1",
    title: "Sunset beach volleyball",
    sport: "volleyball",
    skillLevel: "intermediate",
    gender: "mixed",
    dateTime: "2026-05-18T17:45:00+10:00",
    location: {
      lat: -33.8908,
      lng: 151.2766,
      address: "Marine Parade, Maroubra NSW",
      suburb: "Maroubra Beach",
    },
    distanceKm: 8.6,
    minPlayers: 8,
    maxPlayers: 12,
    currentPlayers: 8,
    costPerPlayer: 300,
    status: "open",
    host: host("host-4", "Zoe Martin"),
  },
  {
    id: "mock-spikeball-1",
    title: "Quick spikeball rounds",
    sport: "spikeball",
    skillLevel: "competitive",
    gender: "open",
    dateTime: "2026-05-20T07:15:00+10:00",
    location: {
      lat: -33.8682,
      lng: 151.2595,
      address: "Murray Rose Pool, Double Bay NSW",
      suburb: "Double Bay Foreshore",
    },
    distanceKm: 4.4,
    minPlayers: 4,
    maxPlayers: 8,
    currentPlayers: 5,
    costPerPlayer: 0,
    status: "open",
    host: host("host-5", "Lucas Hall"),
  },
  {
    id: "mock-basketball-2",
    title: "After-work full court run",
    sport: "basketball",
    skillLevel: "competitive",
    gender: "men",
    dateTime: "2026-05-21T19:00:00+10:00",
    location: {
      lat: -33.8799,
      lng: 151.2061,
      address: "Prince Alfred Park, Surry Hills NSW",
      suburb: "Prince Alfred Park",
    },
    distanceKm: 2.7,
    minPlayers: 8,
    maxPlayers: 10,
    currentPlayers: 10,
    costPerPlayer: 800,
    status: "full",
    host: host("host-6", "Noah Davis"),
  },
];